assets/urls.py
from django.urls import path
from assets import views


app_name = 'assets'


urlpatterns = [
    path('test/', views.test, name='test'),
    path('report/', views.report, name='report'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('index/', views.index, name='index'),
    path('detail/<int:asset_id>/', views.detail, name='detail'),
    path('test1/', views.test1, name="test1"),
    path('txinfo/', views.txinfo, name="txinfo"),
    path('sintask/', views.sintask, name='sintask'),
    path('multtask/', views.multtask, name='multtask'),
    path('api/', views.api, name="api"),
    path('', views.index),
]

assets/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Asset(models.Model):
    """    所有资产的共有数据表    """
    #主机名
    name =  models.CharField(max_length=64, unique=True, verbose_name="资产名称")     # 不可重复
    #环境
    envir = models.CharField(max_length=64, unique=False, verbose_name="主机所在环境")
    #操作系统类型
    ossys =  models.ForeignKey('System', null=True, blank=True, verbose_name='操作系统类型', on_delete=models.SET_NULL)
    #用户名
    userid = models.CharField(max_length=32,unique=False,verbose_name="用户名")
    #密码
    userpasswd =  models.CharField(max_length=32,unique=False,verbose_name="用户密码")
    #内网IP
    ipin = models.CharField(max_length=32,unique=True,verbose_name="内网IP")
    #外网IP
    ipout = models.CharField(max_length=32,unique=False,verbose_name="外网IP")
    #CPU信息
    cpu =  models.CharField(max_length=16,verbose_name="CPU信息")
    #内存信息
    mem = models.CharField(max_length=16,verbose_name="内存")
    #描述信息
    desc =  models.CharField(max_length=32,verbose_name="描述信息")
    #系统盘
    sysdisk = models.CharField(max_length=16,verbose_name="系统盘")
    #数据盘
    datadisk = models.CharField(max_length=16,verbose_name="数据盘")
    #带宽
    bandwidth = models.CharField(max_length=16,verbose_name="带宽")
    #安全组
    secgroup = models.CharField(max_length=16,verbose_name="安全组")
    #分组
    group =  models.CharField(max_length=64,verbose_name="分组")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '资产总表'
        verbose_name_plural = "资产总表"


class System(models.Model):
    name =  models.CharField(max_length=64,verbose_name="操作系统类型")
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '操作系统类型'
        verbose_name_plural = "操作系统类型"

assets/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse,redirect
from django.views.decorators.csrf import csrf_exempt
import json,os
from assets import models
from assets import asset_handler
from django.shortcuts import get_object_or_404
from django.core import serializers


def index(request):
    if not request.session.get('is_login', None):
        return redirect('/login/')
    """
    资产总表视图
    :param request:
    :return:
    """
    assets = models.Asset.objects.all()
    return render(request, 'assets/index.html', locals())


def dashboard(request):
    if not request.session.get('is_login', None):
        return redirect('/login/')

    return render(request, 'assets/dashboard.html', locals())


def detail(request, asset_id):
    if not request.session.get('is_login', None):
        return redirect('/login/')
    """
    以显示服务器类型资产详细为例，安全设备、存储设备、网络设备等参照此例。
    :param request:
    :param asset_id:
    :return:
    """
    #这里注意这个用法！ 固定用法
    asset = get_object_or_404(models.Asset, id=asset_id)
    return render(request, 'assets/detail.html', locals())


@csrf_exempt
def report(request):
    if request.method == 'POST':

        asset_data = request.POST.get('asset_data')
        print(asset_data)
        data = json.loads(asset_data)
        if not data:
            return HttpResponse('没有数据！')
        if not issubclass(dict, type(data)):
            return HttpResponse('数据必须为字典格式！')
        # 你的检测代码

        sn = data.get('sn', None)

        if sn:
            asset_obj = models.Asset.objects.filter(sn=sn)  # [obj]
            if asset_obj:
                update_asset = asset_handler.UpdateAsset(request, asset_obj[0], data)
                return HttpResponse('资产数据已经更新。')
            else:
                obj = asset_handler.NewAsset(request, data)
                response = obj.add_to_new_assets_zone()
                return HttpResponse(response)
        else:
            return HttpResponse('没有资产sn，请检查数据内容！')

    return HttpResponse('200 ok')

import json
def test(request):
    print("请求到达")
    ret = {
        'status': 'success',
        'messa': "服务器返回的数据"
    }

    if request.method == "POST":
        print("post 请求到达")
        data = request.POST.get('data')
        print(data)
        print("111")
        print(request.POST.get('useername'))
    return HttpResponse(json.dumps(ret))


def txinfo(request):
    return render(request, 'assets/ajax_test.html', locals())



def test1(request):
    if not request.session.get('is_login', None):
        return redirect('/login/')
    total = models.Asset.objects.count()
    upline = models.Asset.objects.filter(status=0).count()
    offline = models.Asset.objects.filter(status=1).count()
    unknown = models.Asset.objects.filter(status=2).count()
    breakdown = models.Asset.objects.filter(status=3).count()
    backup = models.Asset.objects.filter(status=4).count()

    up_rate = round(upline/total*100)
    o_rate = round(offline / total * 100)
    un_rate = round(unknown / total * 100)
    bd_rate = round(breakdown / total * 100)
    bu_rate = round(backup / total * 100)

    server_number = models.Server.objects.count()
    networkdevice_number = models.NetworkDevice.objects.count()
    storagedevice_number = models.StorageDevice.objects.count()
    securitydevice_number = models.SecurityDevice.objects.count()
    software_number = models.Software.objects.count()

    return render(request, 'assets/test1.html', locals())

def sintask(request):

    AllServer = models.Asset.objects.count()
    return render(request, 'assets/sintask.html', locals())

def multtask(request):
    AllServer = models.Asset.objects.count()
    return render(request, 'assets/multtask.html', locals())

@csrf_exempt
def api(request):
    print("请求到达")
    ret = {
        'name': 'success',
        'envir': "服务器返回的数据"
    }
    if request.method == "POST" and request.POST.get('mession') == "updatemongo":
        print("post 请求到达")
        from . import mongo
        #更新mongodb里面的数据
        AAA=mongo.UpdateMongo()
        print("there")
        return HttpResponse(json.dumps(ret))
    elif request.method == "POST" and request.POST.get('mession') == "fileupload":
        f_obj = request.FILES.get("f")
        print(f_obj)
        name = f_obj.name
        print(name)
        ftchoice=request.POST.get("ftchoice")
        sechoice=request.POST.get("sechoice")
        global destination
        if ftchoice=="quickbi测试环境" and sechoice=="前端HTML更新":
            if not os.path.isdir("/opt/upload/quickbitest"):
                os.mkdir("/opt/upload/quickbitest")
            destination = open(os.path.join("/opt/upload/quickbitest", name), 'wb+')
        elif ftchoice=="quickbi开发环境" and sechoice == "前端更新":
            destination = open(os.path.join("/opt/upload/quickbidev", name), 'wb+')

        for chunk in f_obj.chunks():  # 分块写入文件
            destination.write(chunk)
        destination.close()

        return HttpResponse("上传成功")

assets/templates/assets/ajax_test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ajax</title>
    <script src="{% static 'assets/jquery.min1.js' %}"></script>
</head>
<body>

<from >
    <input name="username"  />
</from>
<button id="button3">发送post请求</button>



<h3 id="test"> 请点击下面的按钮</h3>

<button id="button1">发送load请求</button>
<br />


<button id="button2">发送get请求</button>

<button id="button4">发送ajax请求</button>


<script>
    $(document).ready(function () {
        $('#button1').click(function () {
            $('#test').load('/static/1.txt',function (data,status,xhr) {
                if(status == 'success'){
                    $(this).text(data);
                }else{
                    $(this).text('load加载失败')
                }

            })

        })

        $('#button2').click(function () {
            <!--  $代表jq 这里表示使用jq的ajx方法-->
            $.get(
                "/assets/test",
            <!--get方法也可以发送数据-->
              {"type":"get"},
                function (data,status) {
                    if(status == 'success'){
                        $('#test').text(JSON.parse(data).messa);
                    }
                    else{
                        $('#test').text('get请求失败')
                    }

                }

            )
        })
        
        $('#button3').click(function () {
            var data = $('input').val();
            $.post(
                '/assets/test/',
                {'type':'post','data':data},
                function () {
                    
                }
            )
            
        })

    })


    <!--ajax方法 发送数据-->
    $('#button4').click(function () {
        $.ajax(
            {
                url:'/assets/test/',
                data:{'useername':'zf','sex':'mail'},
                type:'POST',
                dataType:'json',
                success:function (data) {
<!--注意 这里的data为服务器返回的data! 不是我们发送的data-->
                    console.log(data)
                    $('#test').text(data.messa);

                },
                error:function () {
                    $('#test').text('ajax请求失败')
                },
            }

        )

    })




    function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // 这些HTTP方法不要求CSRF包含
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});




</script>








</body>
</html>

assets/templates/assets/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}资产详细{% endblock %}

{% block css %}

{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        资产详细
        <small>asset info</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li>资产总表</li>
        <li class="active">资产详细</li>
      </ol>
    </section>
{% endblock %}

{% block content %}

     <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">

        <div class="box-header with-border">
            <h3 class="box-title"><strong class="btn btn-block btn-primary btn-lg">资产：{{ asset.name }}</strong></h3>

            <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
            </div>
        </div>

        <div class="box-body">

            <h4><b>概览:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue" >
                <thead>
                    <tr>
                        <th>类型</th>
                        <th>SN</th>
                        <th>业务线</th>
                        <th>制造商</th>
                        <th>管理IP</th>
                        <th>机房</th>
                        <th>标签</th>
                        <th>更新日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.get_asset_type_display }}</td>
                    <td>{{ asset.sn }}</td>
                    <td>{{ asset.business_unit|default:'N/A' }}</td>
                    <td>{{ asset.manufacturer|default:'N/A' }}</td>
                    <td>{{ asset.manage_ip|default:'N/A' }}</td>
                    <td>{{ asset.idc|default:'N/A' }}</td>
                    <td>
                        {% for tag in asset.tags.all %}
                        <label class="label label-primary">{{ tag.name }}</label>
                        {% empty %}
                            -
                        {% endfor %}
                    </td>
                    <td>{{ asset.m_time }}</td>
                </tr>
                </tbody>
            </table>
            <br />
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue">
                <thead>
                    <tr>
                        <th>合同</th>
                        <th>价格</th>
                        <th>购买日期</th>
                        <th>过保日期</th>
                        <th>管理员</th>
                        <th>批准人</th>
                        <th>备注</th>
                        <th>批准日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.contract.name|default:'N/A' }}</td>
                    <td>{{ asset.price|default:'N/A' }}</td>
                    <td>{{ asset.purchase_day|default:'N/A' }}</td>
                    <td>{{ asset.expire_day|default:'N/A' }}</td>
                    <td>{{ asset.admin|default:'N/A' }}</td>
                    <td>{{ asset.approved_by|default:'N/A' }}</td>
                    <td>{{ asset.memo|default:'N/A' }}</td>
                    <td>{{ asset.m_time }}</td>
                </tr>
                </tbody>
            </table>

            <h4><b>服务器:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid green;border-bottom:1px solid green">
                <thead>
                    <tr>
                        <th>服务器类型</th>
                        <th>型号</th>
                        <th>宿主机</th>
                        <th>Raid类型</th>
                        <th>OS类型</th>
                        <th>OS发行版本</th>
                        <th>OS版本</th>
                        <th>添加方式</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.server.get_sub_asset_type_display }}</td>
                    <td>{{ asset.server.model|default:'N/A' }}</td>
                    <td>{{ asset.server.hosted_on.id|default:'N/A' }}</td>
                    <td>{{ asset.server.raid_type|default:'N/A' }}</td>
                    <td>{{ asset.server.os_type|default:'N/A' }}</td>
                    <td>{{ asset.server.os_distribution|default:'N/A' }}</td>
                    <td>{{ asset.server.os_release|default:'N/A' }}</td>
                    <td>{{ asset.server.get_created_by_display }}</td>
                </tr>
                </tbody>
            </table>

            <h4><b>CPU:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid purple;border-bottom:1px solid purple">
                <thead>
                    <tr>
                        <th  style="width: 45%">CPU型号</th>
                        <th  style="width: 15%">物理CPU个数</th>
                        <th>CPU核数</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.cpu.cpu_model|default:'N/A' }}</td>
                    <td>{{ asset.cpu.cpu_count|default:'1' }}</td>
                    <td>{{ asset.cpu.cpu_core_count|default:'1' }}</td>
                </tr>
                </tbody>
            </table>

            <h4><b>内存:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid orangered;border-bottom:1px solid orangered">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>型号</th>
                        <th>容量</th>
                        <th>插槽</th>
                        <th>制造商</th>
                        <th>SN</th>
                    </tr>
                </thead>
                <tbody>
                {% for ram in asset.ram_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ ram.model|default:'N/A' }}</td>
                        <td>{{ ram.capacity|default:'N/A' }}</td>
                        <td>{{ ram.slot }}</td>
                        <td>{{ ram.manufacturer|default:'N/A' }}</td>
                        <td>{{ ram.sn|default:'N/A' }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <h4><b>硬盘:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid brown;border-bottom:1px solid brown">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>型号</th>
                        <th>容量</th>
                        <th>插槽</th>
                        <th>接口类型</th>
                        <th>制造商</th>
                        <th>SN</th>
                    </tr>
                </thead>
                <tbody>
                {% for disk in asset.disk_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ disk.model|default:'N/A' }}</td>
                        <td>{{ disk.capacity|default:'N/A' }}</td>
                        <td>{{ disk.slot|default:'N/A'  }}</td>
                        <td>{{ disk.get_interface_type_display }}</td>
                        <td>{{ disk.manufacturer|default:'N/A' }}</td>
                        <td>{{ disk.sn}}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <h4><b>网卡:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid #a59b1a;border-bottom:1px solid #a59b1a">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>名称</th>
                        <th>型号</th>
                        <th>MAC</th>
                        <th>IP</th>
                        <th>掩码</th>
                        <th>绑定地址</th>
                    </tr>
                </thead>
                <tbody>
                {% for nic in asset.nic_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ nic.name|default:'N/A' }}</td>
                        <td>{{ nic.model }}</td>
                        <td>{{ nic.mac  }}</td>
                        <td>{{ nic.ip_address|default:'N/A' }}</td>
                        <td>{{ nic.net_mask|default:'N/A' }}</td>
                        <td>{{ nic.bonding|default:'N/A' }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <!-- /.box-body -->



        <div class="box-footer">
          <i class="fa fa-angle-double-left"></i>&nbsp;&nbsp;<a href="{% url 'assets:index' %}"><strong>返回资产列表页</strong></a>
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->


{% endblock %}

{% block script %}

{% endblock %}

assets/templates/assets/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}资产总表{% endblock %}

<head>
     <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
<!-- jquary datatable X轴滚动条可以实现单行 滚动条显示，否者会出线无限显示的情况 -->
    th, td { white-space: nowrap; }
</head>

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        资产总表
        <small>assets list</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">资产总表</li>
      </ol>
    </section>
{% endblock %}

{% block content %}

   <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

        <div class="box">
        <div class="box-header">
          <h3 class="box-title">资产总表<small>(不含软件)</small></h3>
        <div align="right" style="position:relative;top:10px">
            <button type="button" class="btn btn-success" id="flushdata">点击手动刷新资产信息</button>
        </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">

            <table id="assets_table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>主机域名</th>
                        <th>环境</th>
                        <th>操作系统类型</th>
                        <th>账号</th>
                        <th>密码</th>
                        <th>ip-内网</th>
                        <th>ip-外网</th>
                        <th>CPU</th>
                        <th>内存</th>
                        <th>描述信息</th>
                        <th>系统盘</th>
                        <th>数据盘</th>
                        <th>带宽</th>
                        <th>安全组</th>
                        <th>分组</th>
                    </tr>
                </thead>
                <tbody id="test2">


                {% for asset in assets %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td class="text-green text-bold">{{ asset.name }}</td>
                        <td>{{ asset.envir }}</td>
                        <td><a href="{% url 'assets:detail' asset.id %}">{{ asset.ossys }}</a></td>

                        <td class="text-bold" >{{ asset.userid }}</td>

                        <td>{{ asset.userpasswd|default_if_none:"-" }}</td>

                        <td class="text-blue">{{ asset.ipin }}</td>

                        <td class="text-danger">{{ asset.ipout }}</td>

                        <td>{{ asset.cpu|default:"-" }}</td>

                        <td>{{ asset.mem }}</td>

                        <td>{{ asset.desc }}</td>

                    <td>{{ asset.sysdisk }}</td>
                    <td>{{ asset.datadisk }}</td>
                    <td>{{ asset.bandwidth }}</td>
                    <td>{{ asset.secgroup }}</td>
                    <td>{{ asset.group }}</td>

                    </tr>

                {% empty %}
                <tr>没有数据</tr>
                {% endfor %}

                </tbody>
                <tfoot>
                    <tr>
                                                <th>序号</th>
                        <th>主机域名</th>
                        <th>环境</th>
                        <th>操作系统类型</th>
                        <th>账号</th>
                        <th>密码</th>
                        <th>ip-内网</th>
                        <th>ip-外网</th>
                        <th>CPU</th>
                        <th>内存</th>
                        <th>描述信息</th>
                        <th>系统盘</th>
                        <th>数据盘</th>
                        <th>带宽</th>
                        <th>安全组</th>
                        <th>分组</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
        </div>
    <!-- /.col -->
      </div>
    <!-- /.row -->
    </section>

{% endblock %}

{% block script %}

<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>

<script>

$(function () {
        $('#assets_table').DataTable({
          "paging": true,       <!-- 允许分页 -->
          "lengthChange": true, <!-- 允许改变每页显示的行数 -->
          "searching": true,    <!-- 允许内容搜索 -->
          "ordering": true,     <!-- 允许排序 -->
          "info": true,         <!-- 显示信息 -->
          "autoWidth": false,    <!-- 固定宽度 -->
          "scrollX":true,   <!--水平滚动-->
          "responsive": false,   <!--关闭响应式效果,否则以上设置无效-->
        });
      });


$('#flushdata').click(function () {
       $.ajax(
            {
                url:'/assets/api/',
                data:{'useername':'zf','mession':'updatemongo'},
                type:'POST',
                dataType:'json',
                success:function (data) {
                    window.location.reload()
                },
                error:function(data){
                    alert("新增失败");
                }
            }
        )
    })


</script>

{% endblock %}

assets/templates/assets/multtask.html
{% extends 'base.html' %}
{% load static %}

{% block title %}仪表盘{% endblock %}
{% block css %} {% endblock %}

{% block breadcrumb %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        任务中心
        <small>jobcenter</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 任务</a></li>
        <li class="active">JOBCENTER</li>
      </ol>
    </section>
{% endblock %}

{% block content %}
  <!-- Main content -->
    <section class="content">
        <div class="row">
            <select id="first" onChange="change()">
            <option selected="selected">quickbi</option>
            <option>标签一代</option>
                <option>标签二代</option>
            </select>

            <select id="second">
                 <option>生产环境重启</option>
                    <option selected="selected">取消缓存</option>
             </select>

      </div>
      <!-- /.row -->

        <form action="/demo/demo_form.asp" id="test1"    >
                    First name:<br>
                <input type="text" name="firstname" value="Mickey">
                <br>
                Last name:<br>
                <input type="text" name="lastname" value="Mouse">
                <br><br>
                <input type="submit" value="Submit">
                </form>
    </section>



<script>
function change()
{
   var x = document.getElementById("first");
   var y = document.getElementById("second");
   y.options.length = 0; // 清除second下拉框的所有内容
   if(x.selectedIndex == 0)
   {
		y.options.add(new Option("生产环境重启", "0"));
		y.options.add(new Option("取消缓存", "1", false, true));  // 默认选中省会城市
   }

   if(x.selectedIndex == 1)
   {


    document.getElementById("idname").style.visibility="visible";
		y.options.add(new Option("test1", "0"));
		y.options.add(new Option("test2", "1", false, true));  // 默认选中省会城市
		y.options.add(new Option("test3", "2"));
   }

}
</script>


{% endblock %}

{% block script %}
<script src="https://cdn.bootcss.com/echarts/4.2.1/echarts.min.js"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/jquery-knob/js/jquery.knob.js' %}"></script>
<script>

</script>
{% endblock %}

assets/templates/assets/test.html
{% extends 'base.html' %}



{% block script %}
    <script>


    $(document).ready(function () {
        $("#nihaoa").hide();

    })
</script>

{% endblock %}

assets/templates/assets/test2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="/upload_ajax/" enctype="multipart/form-data" method="POST">
    <input type="text" name="user" id="user"/>
    <input type="file" name="img" id="img"/>

</form>
    <a style="cursor: pointer;display: inline-block;background-color: black;color: white" onclick="UploadFile1();">XMLHttpRequest上传</a>
    <a style="cursor: pointer;display: inline-block;background-color: black;color: white" onclick="UploadFile2();">jQuery上传</a>
    <script src="/static/jquery-1.12.4.js"></script>
</body>
</html>